### ISSUE TITLE
Mac libltdl.7.dylib not found

### ISSUE THREAD

**Issue by briancordanyoung** [miyako/wak-odbc#2]
When trying to use the example solution, I get the following error:

dyld: Library not loaded: @loader_path/libltdl.7.dylib Referenced from: /Users/byoung/Documents/Code/wak-odbc/SAMPLE/SAMPLE Solution/Modules/odbc/MacOS/isql Reason: image not found 

I tried executing isql from the command line and see the same error.

**Comment by miyako** [comment]
Thank you for pointed that out, I've added the missing file.

**Comment by briancordanyoung** [comment]
Thanks for doing that so quick!  I wish I saw it just as quickly...  Here are more errors after that update:

dyld: Library not loaded: @loader_path/libiconv.2.dylib Referenced from: /Users/byoung/Documents/Code/wak-odbc/SAMPLE/SAMPLE Solution/Modules/odbc/MacOS/isql Reason: Incompatible library version: isql requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0

**Comment by briancordanyoung** [comment]
Actually, I may have some old dylib's on my machine that are conflicting.  I'm trying to clean them off.

**Comment by miyako** [comment]
what you observe is normal,
the iconv shipped with Mac OS (/usr/lib) will be loaded instead
if the dynamic library loader can't find it next to the file that requests it.
I've added 1.14 (=8.0.0) to GitHub as well.

**Comment by briancordanyoung** [comment]
Yes.  That did the trick.  Thank you!
